Repository rstudio/plumber, pull requests merged in 2020-06, with the labels that each got.

#540 getHandle() Speed improvement followup of #484
  NAMESPACE
  NEWS.md
  R/plumber-step.R
Labels: theme:performance:racing_car:

#518 Image serializer
  NEWS.md
  R/find-port.R
  R/images.R
  R/includes.R
  R/parse-block.R
  R/plumber-static.R
  tests/testthat/files/include/test.md
  tests/testthat/test-image.R
  tests/testthat/test-include.R
  tests/testthat/test-static.R
Labels: priority: high

#550 Swaggerfile support for array parameters, object, files. Followup to #532
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/content-types.R
  R/globals.R
  R/json.R
  R/parse-block.R
  R/parse-globals.R
  R/plumber-step.R
  R/plumber.R
  R/post-body.R
  R/post-parsers.R
  R/query-string.R
  R/serializer-json.R
  R/session-cookie.R
  R/swagger.R
  R/zzz.R
  man/PlumberEndpoint.Rd
  man/addParser.Rd
  man/getCharacterSet.Rd
  man/parsers.Rd
  tests/testthat/files/.gitignore
  tests/testthat/files/multipart-form.bin
  tests/testthat/helper-mock-request.R
  tests/testthat/test-parse-block.R
  tests/testthat/test-path-subst.R
  tests/testthat/test-postbody.R
  tests/testthat/test-querystring.R
  tests/testthat/test-sessions.R
  tests/testthat/test-swagger.R
Labels: theme: swagger

#543 Followup to "adds svg plot option #398"
  .github/workflows/R-CMD-check.yaml
  .github/workflows/test-coverage.yaml
  NAMESPACE
  NEWS.md
  R/images.R
  R/parse-block.R
  inst/examples/15-swagger-spec/entrypoint.R
  tests/testthat/files/image.R
  tests/testthat/test-image.R
Labels: type: enhancement
